<?php

namespace Database\Seeders;

use App\Models\Text;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use DateTime;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = new DateTime();
        $now = $now->format('Y-m-d H:i:s');

        $countries = [
            ['code' => 'AF', 'id' => Str::uuid(), 'name' => 'Afghanistan'],
            ['code' => 'AX', 'id' => Str::uuid(), 'name' => 'Aland Islands'],
            ['code' => 'AL', 'id' => Str::uuid(), 'name' => 'Albania'],
            ['code' => 'DZ', 'id' => Str::uuid(), 'name' => 'Algeria'],
            ['code' => 'AS', 'id' => Str::uuid(), 'name' => 'American Samoa'],
            ['code' => 'AD', 'id' => Str::uuid(), 'name' => 'Andorra'],
            ['code' => 'AO', 'id' => Str::uuid(), 'name' => 'Angola'],
            ['code' => 'AI', 'id' => Str::uuid(), 'name' => 'Anguilla'],
            ['code' => 'AQ', 'id' => Str::uuid(), 'name' => 'Antarctica'],
            ['code' => 'AG', 'id' => Str::uuid(), 'name' => 'Antigua and Barbuda'],
            ['code' => 'AR', 'id' => Str::uuid(), 'name' => 'Argentina'],
            ['code' => 'AM', 'id' => Str::uuid(), 'name' => 'Armenia'],
            ['code' => 'AW', 'id' => Str::uuid(), 'name' => 'Aruba'],
            ['code' => 'AU', 'id' => Str::uuid(), 'name' => 'Australia'],
            ['code' => 'AT', 'id' => Str::uuid(), 'name' => 'Austria'],
            ['code' => 'AZ', 'id' => Str::uuid(), 'name' => 'Azerbaijan'],
            ['code' => 'BS', 'id' => Str::uuid(), 'name' => 'Bahamas'],
            ['code' => 'BH', 'id' => Str::uuid(), 'name' => 'Bahrain'],
            ['code' => 'BD', 'id' => Str::uuid(), 'name' => 'Bangladesh'],
            ['code' => 'BB', 'id' => Str::uuid(), 'name' => 'Barbados'],
            ['code' => 'BY', 'id' => Str::uuid(), 'name' => 'Belarus'],
            ['code' => 'BE', 'id' => Str::uuid(), 'name' => 'Belgium'],
            ['code' => 'BZ', 'id' => Str::uuid(), 'name' => 'Belize'],
            ['code' => 'BJ', 'id' => Str::uuid(), 'name' => 'Benin'],
            ['code' => 'BM', 'id' => Str::uuid(), 'name' => 'Bermuda'],
            ['code' => 'BT', 'id' => Str::uuid(), 'name' => 'Bhutan'],
            ['code' => 'BO', 'id' => Str::uuid(), 'name' => 'Bolivia, Plurinational State of'],
            ['code' => 'BQ', 'id' => Str::uuid(), 'name' => 'Bonaire, Sint Eustatius and Saba'],
            ['code' => 'BA', 'id' => Str::uuid(), 'name' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'id' => Str::uuid(), 'name' => 'Botswana'],
            ['code' => 'BV', 'id' => Str::uuid(), 'name' => 'Bouvet Island'],
            ['code' => 'BR', 'id' => Str::uuid(), 'name' => 'Brazil'],
            ['code' => 'IO', 'id' => Str::uuid(), 'name' => 'British Indian Ocean Territory'],
            ['code' => 'BN', 'id' => Str::uuid(), 'name' => 'Brunei Darussalam'],
            ['code' => 'BG', 'id' => Str::uuid(), 'name' => 'Bulgaria'],
            ['code' => 'BF', 'id' => Str::uuid(), 'name' => 'Burkina Faso'],
            ['code' => 'BI', 'id' => Str::uuid(), 'name' => 'Burundi'],
            ['code' => 'KH', 'id' => Str::uuid(), 'name' => 'Cambodia'],
            ['code' => 'CM', 'id' => Str::uuid(), 'name' => 'Cameroon'],
            ['code' => 'CA', 'id' => Str::uuid(), 'name' => 'Canada'],
            ['code' => 'CV', 'id' => Str::uuid(), 'name' => 'Cape Verde'],
            ['code' => 'KY', 'id' => Str::uuid(), 'name' => 'Cayman Islands'],
            ['code' => 'CF', 'id' => Str::uuid(), 'name' => 'Central African Republic'],
            ['code' => 'TD', 'id' => Str::uuid(), 'name' => 'Chad'],
            ['code' => 'CL', 'id' => Str::uuid(), 'name' => 'Chile'],
            ['code' => 'CN', 'id' => Str::uuid(), 'name' => 'China'],
            ['code' => 'CX', 'id' => Str::uuid(), 'name' => 'Christmas Island'],
            ['code' => 'CC', 'id' => Str::uuid(), 'name' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'id' => Str::uuid(), 'name' => 'Colombia'],
            ['code' => 'KM', 'id' => Str::uuid(), 'name' => 'Comoros'],
            ['code' => 'CG', 'id' => Str::uuid(), 'name' => 'Congo'],
            ['code' => 'CD', 'id' => Str::uuid(), 'name' => 'Congo, the Democratic Republic of the'],
            ['code' => 'CK', 'id' => Str::uuid(), 'name' => 'Cook Islands'],
            ['code' => 'CR', 'id' => Str::uuid(), 'name' => 'Costa Rica'],
            ['code' => 'CI', 'id' => Str::uuid(), 'name' => 'Côte d\'Ivoire'],
            ['code' => 'HR', 'id' => Str::uuid(), 'name' => 'Croatia'],
            ['code' => 'CU', 'id' => Str::uuid(), 'name' => 'Cuba'],
            ['code' => 'CW', 'id' => Str::uuid(), 'name' => 'Curaçao'],
            ['code' => 'CY', 'id' => Str::uuid(), 'name' => 'Cyprus'],
            ['code' => 'CZ', 'id' => Str::uuid(), 'name' => 'Czech Republic'],
            ['code' => 'DK', 'id' => Str::uuid(), 'name' => 'Denmark'],
            ['code' => 'DJ', 'id' => Str::uuid(), 'name' => 'Djibouti'],
            ['code' => 'DM', 'id' => Str::uuid(), 'name' => 'Dominica'],
            ['code' => 'DO', 'id' => Str::uuid(), 'name' => 'Dominican Republic'],
            ['code' => 'EC', 'id' => Str::uuid(), 'name' => 'Ecuador'],
            ['code' => 'EG', 'id' => Str::uuid(), 'name' => 'Egypt'],
            ['code' => 'SV', 'id' => Str::uuid(), 'name' => 'El Salvador'],
            ['code' => 'GQ', 'id' => Str::uuid(), 'name' => 'Equatorial Guinea'],
            ['code' => 'ER', 'id' => Str::uuid(), 'name' => 'Eritrea'],
            ['code' => 'EE', 'id' => Str::uuid(), 'name' => 'Estonia'],
            ['code' => 'ET', 'id' => Str::uuid(), 'name' => 'Ethiopia'],
            ['code' => 'FK', 'id' => Str::uuid(), 'name' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FO', 'id' => Str::uuid(), 'name' => 'Faroe Islands'],
            ['code' => 'FJ', 'id' => Str::uuid(), 'name' => 'Fiji'],
            ['code' => 'FI', 'id' => Str::uuid(), 'name' => 'Finland'],
            ['code' => 'FR', 'id' => Str::uuid(), 'name' => 'France'],
            ['code' => 'GF', 'id' => Str::uuid(), 'name' => 'French Guiana'],
            ['code' => 'PF', 'id' => Str::uuid(), 'name' => 'French Polynesia'],
            ['code' => 'TF', 'id' => Str::uuid(), 'name' => 'French Southern Territories'],
            ['code' => 'GA', 'id' => Str::uuid(), 'name' => 'Gabon'],
            ['code' => 'GM', 'id' => Str::uuid(), 'name' => 'Gambia'],
            ['code' => 'GE', 'id' => Str::uuid(), 'name' => 'Georgia'],
            ['code' => 'DE', 'id' => Str::uuid(), 'name' => 'Germany'],
            ['code' => 'GH', 'id' => Str::uuid(), 'name' => 'Ghana'],
            ['code' => 'GI', 'id' => Str::uuid(), 'name' => 'Gibraltar'],
            ['code' => 'GR', 'id' => Str::uuid(), 'name' => 'Greece'],
            ['code' => 'GL', 'id' => Str::uuid(), 'name' => 'Greenland'],
            ['code' => 'GD', 'id' => Str::uuid(), 'name' => 'Grenada'],
            ['code' => 'GP', 'id' => Str::uuid(), 'name' => 'Guadeloupe'],
            ['code' => 'GU', 'id' => Str::uuid(), 'name' => 'Guam'],
            ['code' => 'GT', 'id' => Str::uuid(), 'name' => 'Guatemala'],
            ['code' => 'GG', 'id' => Str::uuid(), 'name' => 'Guernsey'],
            ['code' => 'GN', 'id' => Str::uuid(), 'name' => 'Guinea'],
            ['code' => 'GW', 'id' => Str::uuid(), 'name' => 'Guinea-Bissau'],
            ['code' => 'GY', 'id' => Str::uuid(), 'name' => 'Guyana'],
            ['code' => 'HT', 'id' => Str::uuid(), 'name' => 'Haiti'],
            ['code' => 'HM', 'id' => Str::uuid(), 'name' => 'Heard Island and McDonald Mcdonald Islands'],
            ['code' => 'VA', 'id' => Str::uuid(), 'name' => 'Holy See (Vatican City State)'],
            ['code' => 'HN', 'id' => Str::uuid(), 'name' => 'Honduras'],
            ['code' => 'HK', 'id' => Str::uuid(), 'name' => 'Hong Kong'],
            ['code' => 'HU', 'id' => Str::uuid(), 'name' => 'Hungary'],
            ['code' => 'IS', 'id' => Str::uuid(), 'name' => 'Iceland'],
            ['code' => 'IN', 'id' => Str::uuid(), 'name' => 'India'],
            ['code' => 'ID', 'id' => Str::uuid(), 'name' => 'Indonesia'],
            ['code' => 'IR', 'id' => Str::uuid(), 'name' => 'Iran, Islamic Republic of'],
            ['code' => 'IQ', 'id' => Str::uuid(), 'name' => 'Iraq'],
            ['code' => 'IE', 'id' => Str::uuid(), 'name' => 'Ireland'],
            ['code' => 'IM', 'id' => Str::uuid(), 'name' => 'Isle of Man'],
            ['code' => 'IL', 'id' => Str::uuid(), 'name' => 'Israel'],
            ['code' => 'IT', 'id' => Str::uuid(), 'name' => 'Italy'],
            ['code' => 'JM', 'id' => Str::uuid(), 'name' => 'Jamaica'],
            ['code' => 'JP', 'id' => Str::uuid(), 'name' => 'Japan'],
            ['code' => 'JE', 'id' => Str::uuid(), 'name' => 'Jersey'],
            ['code' => 'JO', 'id' => Str::uuid(), 'name' => 'Jordan'],
            ['code' => 'KZ', 'id' => Str::uuid(), 'name' => 'Kazakhstan'],
            ['code' => 'KE', 'id' => Str::uuid(), 'name' => 'Kenya'],
            ['code' => 'KI', 'id' => Str::uuid(), 'name' => 'Kiribati'],
            ['code' => 'KP', 'id' => Str::uuid(), 'name' => 'Korea, Democratic People\'s Republic of'],
            ['code' => 'KR', 'id' => Str::uuid(), 'name' => 'Korea, Republic of'],
            ['code' => 'KW', 'id' => Str::uuid(), 'name' => 'Kuwait'],
            ['code' => 'KG', 'id' => Str::uuid(), 'name' => 'Kyrgyzstan'],
            ['code' => 'LA', 'id' => Str::uuid(), 'name' => 'Lao People\'s Democratic Republic'],
            ['code' => 'LV', 'id' => Str::uuid(), 'name' => 'Latvia'],
            ['code' => 'LB', 'id' => Str::uuid(), 'name' => 'Lebanon'],
            ['code' => 'LS', 'id' => Str::uuid(), 'name' => 'Lesotho'],
            ['code' => 'LR', 'id' => Str::uuid(), 'name' => 'Liberia'],
            ['code' => 'LY', 'id' => Str::uuid(), 'name' => 'Libya'],
            ['code' => 'LI', 'id' => Str::uuid(), 'name' => 'Liechtenstein'],
            ['code' => 'LT', 'id' => Str::uuid(), 'name' => 'Lithuania'],
            ['code' => 'LU', 'id' => Str::uuid(), 'name' => 'Luxembourg'],
            ['code' => 'MO', 'id' => Str::uuid(), 'name' => 'Macao'],
            ['code' => 'MK', 'id' => Str::uuid(), 'name' => 'Macedonia, the Former Yugoslav Republic of'],
            ['code' => 'MW', 'id' => Str::uuid(), 'name' => 'Malawi'],
            ['code' => 'MG', 'id' => Str::uuid(), 'name' => 'Madagascar'],
            ['code' => 'MY', 'id' => Str::uuid(), 'name' => 'Malaysia'],
            ['code' => 'MV', 'id' => Str::uuid(), 'name' => 'Maldives'],
            ['code' => 'ML', 'id' => Str::uuid(), 'name' => 'Mali'],
            ['code' => 'MT', 'id' => Str::uuid(), 'name' => 'Malta'],
            ['code' => 'MH', 'id' => Str::uuid(), 'name' => 'Marshall Islands'],
            ['code' => 'MQ', 'id' => Str::uuid(), 'name' => 'Martinique'],
            ['code' => 'MR', 'id' => Str::uuid(), 'name' => 'Mauritania'],
            ['code' => 'MU', 'id' => Str::uuid(), 'name' => 'Mauritius'],
            ['code' => 'YT', 'id' => Str::uuid(), 'name' => 'Mayotte'],
            ['code' => 'MX', 'id' => Str::uuid(), 'name' => 'Mexico'],
            ['code' => 'FM', 'id' => Str::uuid(), 'name' => 'Micronesia, Federated States of'],
            ['code' => 'MD', 'id' => Str::uuid(), 'name' => 'Moldova, Republic of'],
            ['code' => 'MC', 'id' => Str::uuid(), 'name' => 'Monaco'],
            ['code' => 'MN', 'id' => Str::uuid(), 'name' => 'Mongolia'],
            ['code' => 'ME', 'id' => Str::uuid(), 'name' => 'Montenegro'],
            ['code' => 'MS', 'id' => Str::uuid(), 'name' => 'Montserrat'],
            ['code' => 'MA', 'id' => Str::uuid(), 'name' => 'Morocco'],
            ['code' => 'MZ', 'id' => Str::uuid(), 'name' => 'Mozambique'],
            ['code' => 'MM', 'id' => Str::uuid(), 'name' => 'Myanmar'],
            ['code' => 'NA', 'id' => Str::uuid(), 'name' => 'Namibia'],
            ['code' => 'NR', 'id' => Str::uuid(), 'name' => 'Nauru'],
            ['code' => 'NP', 'id' => Str::uuid(), 'name' => 'Nepal'],
            ['code' => 'NL', 'id' => Str::uuid(), 'name' => 'Netherlands'],
            ['code' => 'NC', 'id' => Str::uuid(), 'name' => 'New Caledonia'],
            ['code' => 'NZ', 'id' => Str::uuid(), 'name' => 'New Zealand'],
            ['code' => 'NI', 'id' => Str::uuid(), 'name' => 'Nicaragua'],
            ['code' => 'NE', 'id' => Str::uuid(), 'name' => 'Niger'],
            ['code' => 'NG', 'id' => Str::uuid(), 'name' => 'Nigeria'],
            ['code' => 'NU', 'id' => Str::uuid(), 'name' => 'Niue'],
            ['code' => 'NF', 'id' => Str::uuid(), 'name' => 'Norfolk Island'],
            ['code' => 'MP', 'id' => Str::uuid(), 'name' => 'Northern Mariana Islands'],
            ['code' => 'NO', 'id' => Str::uuid(), 'name' => 'Norway'],
            ['code' => 'OM', 'id' => Str::uuid(), 'name' => 'Oman'],
            ['code' => 'PK', 'id' => Str::uuid(), 'name' => 'Pakistan'],
            ['code' => 'PW', 'id' => Str::uuid(), 'name' => 'Palau'],
            ['code' => 'PS', 'id' => Str::uuid(), 'name' => 'Palestine, State of'],
            ['code' => 'PA', 'id' => Str::uuid(), 'name' => 'Panama'],
            ['code' => 'PG', 'id' => Str::uuid(), 'name' => 'Papua New Guinea'],
            ['code' => 'PY', 'id' => Str::uuid(), 'name' => 'Paraguay'],
            ['code' => 'PE', 'id' => Str::uuid(), 'name' => 'Peru'],
            ['code' => 'PH', 'id' => Str::uuid(), 'name' => 'Philippines'],
            ['code' => 'PN', 'id' => Str::uuid(), 'name' => 'Pitcairn'],
            ['code' => 'PL', 'id' => Str::uuid(), 'name' => 'Poland'],
            ['code' => 'PT', 'id' => Str::uuid(), 'name' => 'Portugal'],
            ['code' => 'PR', 'id' => Str::uuid(), 'name' => 'Puerto Rico'],
            ['code' => 'QA', 'id' => Str::uuid(), 'name' => 'Qatar'],
            ['code' => 'RE', 'id' => Str::uuid(), 'name' => 'Réunion'],
            ['code' => 'RO', 'id' => Str::uuid(), 'name' => 'Romania'],
            ['code' => 'RU', 'id' => Str::uuid(), 'name' => 'Russian Federation'],
            ['code' => 'RW', 'id' => Str::uuid(), 'name' => 'Rwanda'],
            ['code' => 'BL', 'id' => Str::uuid(), 'name' => 'Saint Barthélemy'],
            ['code' => 'SH', 'id' => Str::uuid(), 'name' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['code' => 'KN', 'id' => Str::uuid(), 'name' => 'Saint Kitts and Nevis'],
            ['code' => 'LC', 'id' => Str::uuid(), 'name' => 'Saint Lucia'],
            ['code' => 'MF', 'id' => Str::uuid(), 'name' => 'Saint Martin (French part)'],
            ['code' => 'PM', 'id' => Str::uuid(), 'name' => 'Saint Pierre and Miquelon'],
            ['code' => 'VC', 'id' => Str::uuid(), 'name' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'id' => Str::uuid(), 'name' => 'Samoa'],
            ['code' => 'SM', 'id' => Str::uuid(), 'name' => 'San Marino'],
            ['code' => 'ST', 'id' => Str::uuid(), 'name' => 'Sao Tome and Principe'],
            ['code' => 'SA', 'id' => Str::uuid(), 'name' => 'Saudi Arabia'],
            ['code' => 'SN', 'id' => Str::uuid(), 'name' => 'Senegal'],
            ['code' => 'RS', 'id' => Str::uuid(), 'name' => 'Serbia'],
            ['code' => 'SC', 'id' => Str::uuid(), 'name' => 'Seychelles'],
            ['code' => 'SL', 'id' => Str::uuid(), 'name' => 'Sierra Leone'],
            ['code' => 'SG', 'id' => Str::uuid(), 'name' => 'Singapore'],
            ['code' => 'SX', 'id' => Str::uuid(), 'name' => 'Sint Maarten (Dutch part)'],
            ['code' => 'SK', 'id' => Str::uuid(), 'name' => 'Slovakia'],
            ['code' => 'SI', 'id' => Str::uuid(), 'name' => 'Slovenia'],
            ['code' => 'SB', 'id' => Str::uuid(), 'name' => 'Solomon Islands'],
            ['code' => 'SO', 'id' => Str::uuid(), 'name' => 'Somalia'],
            ['code' => 'ZA', 'id' => Str::uuid(), 'name' => 'South Africa'],
            ['code' => 'GS', 'id' => Str::uuid(), 'name' => 'South Georgia and the South Sandwich Islands'],
            ['code' => 'SS', 'id' => Str::uuid(), 'name' => 'South Sudan'],
            ['code' => 'ES', 'id' => Str::uuid(), 'name' => 'Spain'],
            ['code' => 'LK', 'id' => Str::uuid(), 'name' => 'Sri Lanka'],
            ['code' => 'SD', 'id' => Str::uuid(), 'name' => 'Sudan'],
            ['code' => 'SR', 'id' => Str::uuid(), 'name' => 'Suriname'],
            ['code' => 'SJ', 'id' => Str::uuid(), 'name' => 'Svalbard and Jan Mayen'],
            ['code' => 'SZ', 'id' => Str::uuid(), 'name' => 'Swaziland'],
            ['code' => 'SE', 'id' => Str::uuid(), 'name' => 'Sweden'],
            ['code' => 'CH', 'id' => Str::uuid(), 'name' => 'Switzerland'],
            ['code' => 'SY', 'id' => Str::uuid(), 'name' => 'Syrian Arab Republic'],
            ['code' => 'TW', 'id' => Str::uuid(), 'name' => 'Taiwan'],
            ['code' => 'TJ', 'id' => Str::uuid(), 'name' => 'Tajikistan'],
            ['code' => 'TZ', 'id' => Str::uuid(), 'name' => 'Tanzania, United Republic of'],
            ['code' => 'TH', 'id' => Str::uuid(), 'name' => 'Thailand'],
            ['code' => 'TL', 'id' => Str::uuid(), 'name' => 'Timor-Leste'],
            ['code' => 'TG', 'id' => Str::uuid(), 'name' => 'Togo'],
            ['code' => 'TK', 'id' => Str::uuid(), 'name' => 'Tokelau'],
            ['code' => 'TO', 'id' => Str::uuid(), 'name' => 'Tonga'],
            ['code' => 'TT', 'id' => Str::uuid(), 'name' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'id' => Str::uuid(), 'name' => 'Tunisia'],
            ['code' => 'TR', 'id' => Str::uuid(), 'name' => 'Turkey'],
            ['code' => 'TM', 'id' => Str::uuid(), 'name' => 'Turkmenistan'],
            ['code' => 'TC', 'id' => Str::uuid(), 'name' => 'Turks and Caicos Islands'],
            ['code' => 'TV', 'id' => Str::uuid(), 'name' => 'Tuvalu'],
            ['code' => 'UG', 'id' => Str::uuid(), 'name' => 'Uganda'],
            ['code' => 'UA', 'id' => Str::uuid(), 'name' => 'Ukraine'],
            ['code' => 'AE', 'id' => Str::uuid(), 'name' => 'United Arab Emirates'],
            ['code' => 'GB', 'id' => Str::uuid(), 'name' => 'United Kingdom'],
            ['code' => 'US', 'id' => Str::uuid(), 'name' => 'United States'],
            ['code' => 'UM', 'id' => Str::uuid(), 'name' => 'United States Minor Outlying Islands'],
            ['code' => 'UY', 'id' => Str::uuid(), 'name' => 'Uruguay'],
            ['code' => 'UZ', 'id' => Str::uuid(), 'name' => 'Uzbekistan'],
            ['code' => 'VU', 'id' => Str::uuid(), 'name' => 'Vanuatu'],
            ['code' => 'VE', 'id' => Str::uuid(), 'name' => 'Venezuela, Bolivarian Republic of'],
            ['code' => 'VN', 'id' => Str::uuid(), 'name' => 'Viet Nam'],
            ['code' => 'VG', 'id' => Str::uuid(), 'name' => 'Virgin Islands, British'],
            ['code' => 'VI', 'id' => Str::uuid(), 'name' => 'Virgin Islands, U.S.'],
            ['code' => 'WF', 'id' => Str::uuid(), 'name' => 'Wallis and Futuna'],
            ['code' => 'EH', 'id' => Str::uuid(), 'name' => 'Western Sahara'],
            ['code' => 'YE', 'id' => Str::uuid(), 'name' => 'Yemen'],
            ['code' => 'ZM', 'id' => Str::uuid(), 'name' => 'Zambia'],
            ['code' => 'ZW', 'id' => Str::uuid(), 'name' => 'Zimbabwe'],
        ];
 
        DB::table('countries')->insert($countries);
    }
}