<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $now = new DateTime();
        // $now = $now->format('Y-m-d H:i:s');
 
        $languages = [
            ['code' => 'ab', 'id' => Str::uuid(), 'name' => 'Abkhazian'],
            ['code' => 'aa', 'id' => Str::uuid(), 'name' => 'Afar'],
            ['code' => 'af', 'id' => Str::uuid(), 'name' => 'Afrikaans'],
            ['code' => 'ak', 'id' => Str::uuid(), 'name' => 'Akan'],
            ['code' => 'sq', 'id' => Str::uuid(), 'name' => 'Albanian'],
            ['code' => 'am', 'id' => Str::uuid(), 'name' => 'Amharic'],
            ['code' => 'ar', 'id' => Str::uuid(), 'name' => 'Arabic'],
            ['code' => 'an', 'id' => Str::uuid(), 'name' => 'Aragonese'],
            ['code' => 'hy', 'id' => Str::uuid(), 'name' => 'Armenian'],
            ['code' => 'as', 'id' => Str::uuid(), 'name' => 'Assamese'],
            ['code' => 'av', 'id' => Str::uuid(), 'name' => 'Avaric'],
            ['code' => 'ae', 'id' => Str::uuid(), 'name' => 'Avestan'],
            ['code' => 'ay', 'id' => Str::uuid(), 'name' => 'Aymara'],
            ['code' => 'az', 'id' => Str::uuid(), 'name' => 'Azerbaijani'],
            ['code' => 'bm', 'id' => Str::uuid(), 'name' => 'Bambara'],
            ['code' => 'ba', 'id' => Str::uuid(), 'name' => 'Bashkir'],
            ['code' => 'eu', 'id' => Str::uuid(), 'name' => 'Basque'],
            ['code' => 'be', 'id' => Str::uuid(), 'name' => 'Belarusian'],
            ['code' => 'bn', 'id' => Str::uuid(), 'name' => 'Bengali'],
            ['code' => 'bi', 'id' => Str::uuid(), 'name' => 'Bislama'],
            ['code' => 'bs', 'id' => Str::uuid(), 'name' => 'Bosnian'],
            ['code' => 'br', 'id' => Str::uuid(), 'name' => 'Breton'],
            ['code' => 'bg', 'id' => Str::uuid(), 'name' => 'Bulgarian'],
            ['code' => 'my', 'id' => Str::uuid(), 'name' => 'Burmese'],
            ['code' => 'ca', 'id' => Str::uuid(), 'name' => 'Catalan'],
            ['code' => 'ch', 'id' => Str::uuid(), 'name' => 'Chamorro'],
            ['code' => 'ce', 'id' => Str::uuid(), 'name' => 'Chechen'],
            ['code' => 'ny', 'id' => Str::uuid(), 'name' => 'Chichewa'],
            ['code' => 'zh', 'id' => Str::uuid(), 'name' => 'Chinese'],
            ['code' => 'cu', 'id' => Str::uuid(), 'name' => 'Church Slavic'],
            ['code' => 'cv', 'id' => Str::uuid(), 'name' => 'Chuvash'],
            ['code' => 'kw', 'id' => Str::uuid(), 'name' => 'Cornish'],
            ['code' => 'co', 'id' => Str::uuid(), 'name' => 'Corsican'],
            ['code' => 'cr', 'id' => Str::uuid(), 'name' => 'Cree'],
            ['code' => 'hr', 'id' => Str::uuid(), 'name' => 'Croatian'],
            ['code' => 'cs', 'id' => Str::uuid(), 'name' => 'Czech'],
            ['code' => 'da', 'id' => Str::uuid(), 'name' => 'Danish'],
            [ 'code' => 'v', 'id' => Str::uuid(), 'name' => 'Divehi'],
            ['code' => 'nl', 'id' => Str::uuid(), 'name' => 'Dutch'],
            ['code' => 'dz', 'id' => Str::uuid(), 'name' => 'Dzongkha'],
            ['code' => 'en', 'id' => Str::uuid(), 'name' => 'English'],
            ['code' => 'eo', 'id' => Str::uuid(), 'name' => 'Esperanto'],
            ['code' => 'et', 'id' => Str::uuid(), 'name' => 'Estonian'],
            ['code' => 'ee', 'id' => Str::uuid(), 'name' => 'Ewe'],
            ['code' => 'fo', 'id' => Str::uuid(), 'name' => 'Faroese'],
            ['code' => 'fj', 'id' => Str::uuid(), 'name' => 'Fijian'],
            ['code' => 'fi', 'id' => Str::uuid(), 'name' => 'Finnish'],
            ['code' => 'fr', 'id' => Str::uuid(), 'name' => 'French'],
            ['code' => 'fy', 'id' => Str::uuid(), 'name' => 'Western Frisian'],
            ['code' => 'ff', 'id' => Str::uuid(), 'name' => 'Fulah'],
            ['code' => 'gd', 'id' => Str::uuid(), 'name' => 'Gaelic'],
            ['code' => 'gl', 'id' => Str::uuid(), 'name' => 'Galician'],
            ['code' => 'lg', 'id' => Str::uuid(), 'name' => 'Ganda'],
            ['code' => 'ka', 'id' => Str::uuid(), 'name' => 'Georgian'],
            ['code' => 'de', 'id' => Str::uuid(), 'name' => 'German'],
            ['code' => 'el', 'id' => Str::uuid(), 'name' => 'Greek'],
            ['code' => 'kl', 'id' => Str::uuid(), 'name' => 'Kalaallisut'],
            ['code' => 'gn', 'id' => Str::uuid(), 'name' => 'Guarani'],
            ['code' => 'gu', 'id' => Str::uuid(), 'name' => 'Gujarati'],
            ['code' => 'ht', 'id' => Str::uuid(), 'name' => 'Haitian'],
            ['code' => 'ha', 'id' => Str::uuid(), 'name' => 'Hausa'],
            ['code' => 'he', 'id' => Str::uuid(), 'name' => 'Hebrew'],
            ['code' => 'hz', 'id' => Str::uuid(), 'name' => 'Herero'],
            ['code' => 'hi', 'id' => Str::uuid(), 'name' => 'Hindi'],
            ['code' => 'ho', 'id' => Str::uuid(), 'name' => 'Hiri Motu'],
            ['code' => 'hu', 'id' => Str::uuid(), 'name' => 'Hungarian'],
            ['code' => 'is', 'id' => Str::uuid(), 'name' => 'Icelandic'],
            ['code' => 'io', 'id' => Str::uuid(), 'name' => 'Ido'],
            ['code' => 'ig', 'id' => Str::uuid(), 'name' => 'Igbo'],
            ['code' => 'id', 'id' => Str::uuid(), 'name' => 'Indonesian'],
            ['code' => 'ia', 'id' => Str::uuid(), 'name' => 'Interlingua'],
            ['code' => 'ie', 'id' => Str::uuid(), 'name' => 'Interlingue'],
            ['code' => 'iu', 'id' => Str::uuid(), 'name' => 'Inuktitut'],
            ['code' => 'ik', 'id' => Str::uuid(), 'name' => 'Inupiaq'],
            ['code' => 'ga', 'id' => Str::uuid(), 'name' => 'Irish'],
            ['code' => 'it', 'id' => Str::uuid(), 'name' => 'Italian'],
            ['code' => 'ja', 'id' => Str::uuid(), 'name' => 'Japanese'],
            ['code' => 'jv', 'id' => Str::uuid(), 'name' => 'Javanese'],
            ['code' => 'kn', 'id' => Str::uuid(), 'name' => 'Kannada'],
            ['code' => 'kr', 'id' => Str::uuid(), 'name' => 'Kanuri'],
            ['code' => 'ks', 'id' => Str::uuid(), 'name' => 'Kashmiri'],
            ['code' => 'kk', 'id' => Str::uuid(), 'name' => 'Kazakh'],
            ['code' => 'km', 'id' => Str::uuid(), 'name' => 'Central Khmer'],
            ['code' => 'ki', 'id' => Str::uuid(), 'name' => 'Kikuyu'],
            ['code' => 'rw', 'id' => Str::uuid(), 'name' => 'Kinyarwanda'],
            ['code' => 'ky', 'id' => Str::uuid(), 'name' => 'Kirghiz'],
            ['code' => 'kv', 'id' => Str::uuid(), 'name' => 'Komi'],
            ['code' => 'kg', 'id' => Str::uuid(), 'name' => 'Kongo'],
            ['code' => 'ko', 'id' => Str::uuid(), 'name' => 'Korean'],
            ['code' => 'kj', 'id' => Str::uuid(), 'name' => 'Kuanyama'],
            ['code' => 'ku', 'id' => Str::uuid(), 'name' => 'Kurdish'],
            ['code' => 'lo', 'id' => Str::uuid(), 'name' => 'Lao'],
            ['code' => 'la', 'id' => Str::uuid(), 'name' => 'Latin'],
            ['code' => 'lv', 'id' => Str::uuid(), 'name' => 'Latvian'],
            ['code' => 'li', 'id' => Str::uuid(), 'name' => 'Limburgan'],
            ['code' => 'ln', 'id' => Str::uuid(), 'name' => 'Lingala'],
            ['code' => 'lt', 'id' => Str::uuid(), 'name' => 'Lithuanian'],
            ['code' => 'lu', 'id' => Str::uuid(), 'name' => 'Luba-Katanga'],
            ['code' => 'lb', 'id' => Str::uuid(), 'name' => 'Luxembourgish'],
            ['code' => 'mk', 'id' => Str::uuid(), 'name' => 'Macedonian'],
            ['code' => 'mg', 'id' => Str::uuid(), 'name' => 'Malagasy'],
            ['code' => 'ms', 'id' => Str::uuid(), 'name' => 'Malay'],
            ['code' => 'ml', 'id' => Str::uuid(), 'name' => 'Malayalam'],
            ['code' => 'mt', 'id' => Str::uuid(), 'name' => 'Maltese'],
            ['code' => 'gv', 'id' => Str::uuid(), 'name' => 'Manx'],
            ['code' => 'mi', 'id' => Str::uuid(), 'name' => 'Maori'],
            ['code' => 'mr', 'id' => Str::uuid(), 'name' => 'Marathi'],
            ['code' => 'mh', 'id' => Str::uuid(), 'name' => 'Marshallese'],
            ['code' => 'mn', 'id' => Str::uuid(), 'name' => 'Mongolian'],
            ['code' => 'na', 'id' => Str::uuid(), 'name' => 'Nauru'],
            ['code' => 'nv', 'id' => Str::uuid(), 'name' => 'Navajo'],
            ['code' => 'nd', 'id' => Str::uuid(), 'name' => 'North Ndebele'],
            ['code' => 'nr', 'id' => Str::uuid(), 'name' => 'South Ndebele'],
            ['code' => 'ng', 'id' => Str::uuid(), 'name' => 'Ndonga'],
            ['code' => 'ne', 'id' => Str::uuid(), 'name' => 'Nepali'],
            ['code' => 'no', 'id' => Str::uuid(), 'name' => 'Norwegian'],
            ['code' => 'nb', 'id' => Str::uuid(), 'name' => 'Norwegian Bokmål'],
            ['code' => 'nn', 'id' => Str::uuid(), 'name' => 'Norwegian Nynorsk'],
            ['code' => 'ii', 'id' => Str::uuid(), 'name' => 'Sichuan Yi'],
            ['code' => 'oc', 'id' => Str::uuid(), 'name' => 'Occitan'],
            ['code' => 'oj', 'id' => Str::uuid(), 'name' => 'Ojibwa'],
            ['code' => 'or', 'id' => Str::uuid(), 'name' => 'Oriya'],
            ['code' => 'om', 'id' => Str::uuid(), 'name' => 'Oromo'],
            ['code' => 'os', 'id' => Str::uuid(), 'name' => 'Ossetian'],
            ['code' => 'pi', 'id' => Str::uuid(), 'name' => 'Pali'],
            ['code' => 'ps', 'id' => Str::uuid(), 'name' => 'Pashto'],
            ['code' => 'fa', 'id' => Str::uuid(), 'name' => 'Persian'],
            ['code' => 'pl', 'id' => Str::uuid(), 'name' => 'Polish'],
            ['code' => 'pt', 'id' => Str::uuid(), 'name' => 'Portuguese'],
            ['code' => 'pa', 'id' => Str::uuid(), 'name' => 'Punjabi'],
            ['code' => 'qu', 'id' => Str::uuid(), 'name' => 'Quechua'],
            ['code' => 'ro', 'id' => Str::uuid(), 'name' => 'Romanian'],
            ['code' => 'rm', 'id' => Str::uuid(), 'name' => 'Romansh'],
            ['code' => 'rn', 'id' => Str::uuid(), 'name' => 'Rundi'],
            ['code' => 'ru', 'id' => Str::uuid(), 'name' => 'Russian'],
            ['code' => 'se', 'id' => Str::uuid(), 'name' => 'Northern Sami'],
            ['code' => 'sm', 'id' => Str::uuid(), 'name' => 'Samoan'],
            ['code' => 'sg', 'id' => Str::uuid(), 'name' => 'Sango'],
            ['code' => 'sa', 'id' => Str::uuid(), 'name' => 'Sanskrit'],
            ['code' => 'sc', 'id' => Str::uuid(), 'name' => 'Sardinian'],
            ['code' => 'sr', 'id' => Str::uuid(), 'name' => 'Serbian'],
            ['code' => 'sn', 'id' => Str::uuid(), 'name' => 'Shona'],
            ['code' => 'sd', 'id' => Str::uuid(), 'name' => 'Sindhi'],
            ['code' => 'si', 'id' => Str::uuid(), 'name' => 'Sinhala'],
            ['code' => 'sk', 'id' => Str::uuid(), 'name' => 'Slovak'],
            ['code' => 'sl', 'id' => Str::uuid(), 'name' => 'Slovenian'],
            ['code' => 'so', 'id' => Str::uuid(), 'name' => 'Somali'],
            ['code' => 'st', 'id' => Str::uuid(), 'name' => 'Southern Sotho'],
            ['code' => 'es', 'id' => Str::uuid(), 'name' => 'Spanish'],
            ['code' => 'su', 'id' => Str::uuid(), 'name' => 'Sundanese'],
            ['code' => 'sw', 'id' => Str::uuid(), 'name' => 'Swahili'],
            ['code' => 'ss', 'id' => Str::uuid(), 'name' => 'Swati'],
            ['code' => 'sv', 'id' => Str::uuid(), 'name' => 'Swedish'],
            ['code' => 'tl', 'id' => Str::uuid(), 'name' => 'Tagalog'],
            ['code' => 'ty', 'id' => Str::uuid(), 'name' => 'Tahitian'],
            ['code' => 'tg', 'id' => Str::uuid(), 'name' => 'Tajik'],
            ['code' => 'ta', 'id' => Str::uuid(), 'name' => 'Tamil'],
            ['code' => 'tt', 'id' => Str::uuid(), 'name' => 'Tatar'],
            ['code' => 'te', 'id' => Str::uuid(), 'name' => 'Telugu'],
            ['code' => 'th', 'id' => Str::uuid(), 'name' => 'Thai'],
            ['code' => 'bo', 'id' => Str::uuid(), 'name' => 'Tibetan'],
            ['code' => 'ti', 'id' => Str::uuid(), 'name' => 'Tigrinya'],
            ['code' => 'to', 'id' => Str::uuid(), 'name' => 'Tonga'],
            ['code' => 'ts', 'id' => Str::uuid(), 'name' => 'Tsonga'],
            ['code' => 'tn', 'id' => Str::uuid(), 'name' => 'Tswana'],
            ['code' => 'tr', 'id' => Str::uuid(), 'name' => 'Turkish'],
            ['code' => 'tk', 'id' => Str::uuid(), 'name' => 'Turkmen'],
            ['code' => 'tw', 'id' => Str::uuid(), 'name' => 'Twi'],
            ['code' => 'ug', 'id' => Str::uuid(), 'name' => 'Uighur'],
            ['code' => 'uk', 'id' => Str::uuid(), 'name' => 'Ukrainian'],
            ['code' => 'ur', 'id' => Str::uuid(), 'name' => 'Urdu'],
            ['code' => 'uz', 'id' => Str::uuid(), 'name' => 'Uzbek'],
            ['code' => 've', 'id' => Str::uuid(), 'name' => 'Venda'],
            ['code' => 'vi', 'id' => Str::uuid(), 'name' => 'Vietnamese'],
            ['code' => 'vo', 'id' => Str::uuid(), 'name' => 'Volapük'],
            ['code' => 'wa', 'id' => Str::uuid(), 'name' => 'Walloon'],
            ['code' => 'cy', 'id' => Str::uuid(), 'name' => 'Welsh'],
            ['code' => 'wo', 'id' => Str::uuid(), 'name' => 'Wolof'],
            ['code' => 'xh', 'id' => Str::uuid(), 'name' => 'Xhosa'],
            ['code' => 'yi', 'id' => Str::uuid(), 'name' => 'Yiddish'],
            ['code' => 'yo', 'id' => Str::uuid(), 'name' => 'Yoruba'],
            ['code' => 'za', 'id' => Str::uuid(), 'name' => 'Zhuang'],
            ['code' => 'zu', 'id' => Str::uuid(), 'name' => 'Zulu'],
        ];
 
        DB::table('languages')->insert($languages);
    }
}
